name: dherkin2
version: 1.0.0
authors:
- Danil Kornishev <danil.kornishev@gmail.com>
- Florian Huonder <florian.huonder@prolutions.ch>
- Sacha Dolski <sacha.dolski@prolutions.ch>
description: Gherkin/Cucumber implementation in dart
homepage: https://github.com/prolutionsGmbH/dherkin
dependencies:
  log4dart: ">=1.4.10 <1.5.0"
  args: "1.4.3"
  ansicolor: ">=0.0.9 <0.1.0"
dev_dependencies:
