name: dherkin
version: 0.3.0
author: Danil Kornishev <danil.kornishev@gmail.com>
description: Gherkin/Cucumber implementation in dart
homepage: https://github.com/dkornishev/dherkin
dependencies:
  log4dart: ">=1.4.10 <1.5.0"
  args: ">=0.8.7 < 0.9.0"
  worker:
    git: https://github.com/Dreckr/Worker.git
  #worker: ">=0.3.11 <0.4.0"
  ansicolor: ">=0.0.9 <0.1.0"
dev_dependencies:
