name: dherkin
version: 0.2.1
author: Danil Kornishev <danil.kornishev@gmail.com>
description: Gherkin/Cucumber implementation in dart
homepage: https://github.com/dkornishev/dherkin
dependencies:
  log4dart: ">=1.4.10 <1.5.0"
  args: ">=0.8.7 < 0.9.0"
  worker:
    git: https://github.com/Goutte/Worker.git  # see https://github.com/Dreckr/Worker/issues/12
  #worker: ">=0.3.9 <0.4.0"
dev_dependencies:
