name: ogurets
version: 3.2.1
description: Gherkin/Cucumber implementation in dart, supporting classes and simple libraries, hooks, dependency injection, and all the things you would want in an easy to use format.
homepage: https://github.com/dart-ogurets/Ogurets
dependencies:
  logging: ^0.11.3+2
  args: ^1.5.0
  ansicolor: ^1.0.2
  intl: ">=0.15.8"
  sprintf: "^4.0.0"
environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
