name: ogurets
version: 3.1.5
authors:
- Irina Southwell <pishisuda11@gmail.com>
- Richard Vowles <richard@bluetrainsoftware.com>
- Danil Kornishev <danil.kornishev@gmail.com>
- Florian Huonder <florian.huonder@prolutions.ch>
- Sacha Dolski <sacha.dolski@prolutions.ch>
description: Gherkin/Cucumber implementation in dart, supporting classes and simple libraries, hooks, dependency injection, and all the things you would want in an easy to use format.
homepage: https://github.com/dart-ogurets/Ogurets
dependencies:
  logging: ^0.11.3+2
  args: ^1.5.0
  ansicolor: ^1.0.2
  intl: ^0.15.8
  sprintf: "^4.0.0"
environment:
  sdk: ">=2.2.0 <3.0.0"

dev_dependencies:
#  build_runner: ^1.3.4
#  test: ^1.6.2
